/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetTransactionRouteImport } from './routes/GetTransaction'
import { Route as GetTransactionByReferenceRouteImport } from './routes/GetTransactionByReference'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as PayTransactionIdRouteImport } from './routes/pay/$transactionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetTransactionRoute = GetTransactionRouteImport.update({
  id: '/GetTransaction',
  path: '/GetTransaction',
  getParentRoute: () => rootRouteImport,
} as any)
const GetTransactionByReferenceRoute =
  GetTransactionByReferenceRouteImport.update({
    id: '/GetTransactionByReference',
    path: '/GetTransactionByReference',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTransactionIdRoute = PayTransactionIdRouteImport.update({
  id: '/pay/$transactionId',
  path: '/pay/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/GetTransaction': typeof GetTransactionRoute
  '/GetTransactionByReference': typeof GetTransactionByReferenceRoute
  '/admin': typeof AdminRoute
  '/docs': typeof DocsRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pay/$transactionId': typeof PayTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/GetTransaction': typeof GetTransactionRoute
  '/GetTransactionByReference': typeof GetTransactionByReferenceRoute
  '/admin': typeof AdminRoute
  '/docs': typeof DocsRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pay/$transactionId': typeof PayTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/GetTransaction': typeof GetTransactionRoute
  '/GetTransactionByReference': typeof GetTransactionByReferenceRoute
  '/admin': typeof AdminRoute
  '/docs': typeof DocsRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pay/$transactionId': typeof PayTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/GetTransaction'
    | '/GetTransactionByReference'
    | '/admin'
    | '/docs'
    | '/openapi.json'
    | '/pay/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/GetTransaction'
    | '/GetTransactionByReference'
    | '/admin'
    | '/docs'
    | '/openapi.json'
    | '/pay/$transactionId'
  id:
    | '__root__'
    | '/'
    | '/GetTransaction'
    | '/GetTransactionByReference'
    | '/admin'
    | '/docs'
    | '/openapi.json'
    | '/pay/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetTransactionRoute: typeof GetTransactionRoute
  GetTransactionByReferenceRoute: typeof GetTransactionByReferenceRoute
  AdminRoute: typeof AdminRoute
  DocsRoute: typeof DocsRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  PayTransactionIdRoute: typeof PayTransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GetTransaction': {
      id: '/GetTransaction'
      path: '/GetTransaction'
      fullPath: '/GetTransaction'
      preLoaderRoute: typeof GetTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GetTransactionByReference': {
      id: '/GetTransactionByReference'
      path: '/GetTransactionByReference'
      fullPath: '/GetTransactionByReference'
      preLoaderRoute: typeof GetTransactionByReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$transactionId': {
      id: '/pay/$transactionId'
      path: '/pay/$transactionId'
      fullPath: '/pay/$transactionId'
      preLoaderRoute: typeof PayTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetTransactionRoute: GetTransactionRoute,
  GetTransactionByReferenceRoute: GetTransactionByReferenceRoute,
  AdminRoute: AdminRoute,
  DocsRoute: DocsRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  PayTransactionIdRoute: PayTransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
